# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# NOTE (Simon): UUIDs were manually re-aligned to the actual disk on
# 2026-09-19.  They were previously pointing at a different drive
# (ab52ff06-…/82C1-0B39 + a swap UUID that does not exist), which
# caused “device not found” at boot.
#   root btrfs : 02b5e41e-9251-4a79-8e83-7d5e830cb604 (label "root")
#   /boot vfat : 4739-B5BB
#   swap       : no swap partition; 8 GiB /swapfile (see below)
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/02b5e41e-9251-4a79-8e83-7d5e830cb604";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/02b5e41e-9251-4a79-8e83-7d5e830cb604";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/02b5e41e-9251-4a79-8e83-7d5e830cb604";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4739-B5BB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # 8 GiB swapfile on btrfs - created automatically at boot by the
  # mkswap-... service (btrfs filesystem mkswapfile). Size in MiB.
  swapDevices = [ {
    device = "/swapfile";
    size = 8192;
  } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}